FROM node:12.22.6-buster-slim

LABEL maintainer="support@ilpmatude.com"
LABEL org.label-schema.description="Ilpma CLI"
LABEL org.label-schema.url="https://ilpmatude.com"

RUN npm i -s -g @falconandy/ilpma@latest
RUN ilpma --version
