name: Publish master packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test-ci

      - name: Set registry url
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Get current timestamp
        run: |
          echo "CURRENT_TIMESTAMP=$( date -u +'%Y%m%d%H%M%S' )" >> $GITHUB_ENV

      - name: Publish the GitHub package
        run: |
          npm version prerelease --no-git-tag-version --preid master-${{ env.CURRENT_TIMESTAMP }}
          npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old GitHub packages
        uses: smartsquaregmbh/delete-old-packages@v0.3.2
        with:
          version-pattern: "^\\d+\\.\\d+\\.\\d+-master-[0-9a-f]+\\.\\d+$"
          keep: 1
          names: |
            ilpma

      - name: Get published version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Add tag 'master' to the GitHub package
        run: |
          npm dist-tag add @falconandy/ilpma@${{ steps.package-version.outputs.current-version }} master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create artifactes
        run: |
          yarn oclif-dev pack

      - name: Publish pre-release assets to Homebrew
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: falconandy/homebrew-ilpma
          repo_token: "${{ secrets.HOMEBREW_PUBLISH_TOKEN }}"
          file: dist/**/*.tar.gz
          file_glob: true
          release_name: "Development Build"
          tag: "latest"
          prerelease: true
          overwrite: true

      - name: Checkout homebrew-ilpma
        uses: actions/checkout@v2
        with:
          repository: falconandy/homebrew-ilpma
          path: homebrew-ilpma
          ssh-key: ${{ secrets.HOMEBREW_ILPMA_DEPLOY_KEY }}

      - name: Update Brew formula
        run: |
          npx ts-node ./buildtools/updateBrewFormula.ts --dist ./dist --version ${{ steps.package-version.outputs.current-version }} --formula ./homebrew-ilpma/Formula/ilpma-dev.rb

      - name: Commit Brew formula
        run: |
          cd ./homebrew-ilpma
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m "v${{ steps.package-version.outputs.current-version }}"
          git tag "v${{ steps.package-version.outputs.current-version }}"
          git push
          git push --tags
