name: Publish release artifacts

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ILPMA_DEPLOY_KEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Create artifactes
        run: |
          yarn oclif-dev pack

      - name: Publish artifactes
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/**/*.tar.gz

      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Checkout homebrew-ilpma
        uses: actions/checkout@v2
        with:
          repository: falconandy/homebrew-ilpma
          path: homebrew-ilpma
          ssh-key: ${{ secrets.HOMEBREW_ILPMA_DEPLOY_KEY }}

      - name: Configure Git User
        run: |
          cd ./homebrew-ilpma
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Brew formula
        run: |
          npx ts-node ../buildtools/updateBrewFormula.ts --dist ../dist --version ${{ steps.package-version.outputs.current-version }} --formula ./Formula/ilpma.rb
          git commit -m "v${{ steps.package-version.outputs.current-version }}"
          git tag "v${{ steps.package-version.outputs.current-version }}"
          git push
          git push --tags
