name: Build/Push Docker images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get BUILD_DATE
        run: |
          echo "BUILD_DATE=$( date -u +'%Y-%m-%dT%H:%M:%SZ' )" >> $GITHUB_ENV

      - name: Docker meta ${{ secrets.DOCKERHUB_USERNAME }}/ilpma
        id: meta-ilpma
        uses: docker/metadata-action@v3
        with:
          tags: type=semver,pattern={{version}}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ilpma

      - name: Build and push ${{ secrets.DOCKERHUB_USERNAME }}/ilpma
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ilpma
          push: true
          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
          tags: ${{ steps.meta-ilpma.outputs.tags }}

#      - name: Docker meta ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-dotnet
#        id: meta-dotnet
#        uses: docker/metadata-action@v3
#        with:
#          tags: type=semver,pattern={{version}}
#          images: ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-dotnet
#
#      - name: Build and push ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-dotnet
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/ilpma-dotnet
#          push: true
#          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
#          tags: ${{ steps.meta-dotnet.outputs.tags }}
#
#      - name: Docker meta ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-ruby
#        id: meta-ruby
#        uses: docker/metadata-action@v3
#        with:
#          tags: type=semver,pattern={{version}}
#          images: ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-ruby
#
#      - name: Build and push ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-ruby
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/ilpma-ruby
#          push: true
#          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
#          tags: ${{ steps.meta-ruby.outputs.tags }}
#
#      - name: Docker meta ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-swift
#        id: meta-swift
#        uses: docker/metadata-action@v3
#        with:
#          tags: type=semver,pattern={{version}}
#          images: ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-swift
#
#      - name: Build and push ${{ secrets.DOCKERHUB_USERNAME }}/ilpma-swift
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/ilpma-swift
#          push: true
#          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
#          tags: ${{ steps.meta-swift.outputs.tags }}
