name: Build/Push Docker images

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta @falconandy/ilpma
        id: meta-ilpma
        uses: docker/metadata-action@v3
        with:
          images: falconandy/ilpma

      - name: Build and push falconandy/ilpma
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ilpma
          push: true
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: ${{ steps.meta-ilpma.outputs.tags }}

      - name: Docker meta falconandy/ilpma-dotnet
        id: meta-dotnet
        uses: docker/metadata-action@v3
        with:
          images: falconandy/ilpma-dotnet

      - name: Build and push falconandy/ilpma-dotnet
        uses: docker/build-push-action@v2
        with:
          context: ./docker/dotnet
          push: true
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: ${{ steps.meta-dotnet.outputs.tags }}

      - name: Docker meta falconandy/ilpma-ruby
        id: meta-ruby
        uses: docker/metadata-action@v3
        with:
          images: falconandy/ilpma-ruby

      - name: Build and push falconandy/ilpma-ruby
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruby
          push: true
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: ${{ steps.meta-ruby.outputs.tags }}

      - name: Docker meta falconandy/ilpma-swift
        id: meta-swift
        uses: docker/metadata-action@v3
        with:
          images: falconandy/ilpma-swift

      - name: Build and push falconandy/ilpma-swift
        uses: docker/build-push-action@v2
        with:
          context: ./docker/swift
          push: true
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: ${{ steps.meta-swift.outputs.tags }}
